name: Build and deploy Jekyll site

on:
  push:
    branches: [main]

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Install Dependencies
        run: |
          bundle config path vendor/bundle
          bundle install

      - name: Build with Jekyll
        uses: limjh16/jekyll-action-ts@v2
        with:
          jekyll_src: "./"
          jekyll_env: production
          enable_cache: true